LOCAL_PATH := $(call my-dir)
LIB_PATH := $(LOCAL_PATH)/../lib

include $(CLEAR_VARS)
LOCAL_MODULE := libfmod
LOCAL_EXPORT_C_INCLUDES := ../$(LOCAL_PATH)/TaxiCode/Ext/fmod_android
LOCAL_SRC_FILES := ../$(LOCAL_PATH)/TaxiCode/Ext/fmod_android/$(TARGET_ARCH_ABI)/libfmod.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)

ROOT_FILES  := $(wildcard $(LOCAL_PATH)/*.cpp)
ROOT_FILES  := $(ROOT_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_MATH_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Math/*.cpp)
FRAMEWORK_MATH_FILES := $(FRAMEWORK_MATH_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_GRAPHICS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Graphics/*.cpp)
FRAMEWORK_GRAPHICS_FILES := $(FRAMEWORK_GRAPHICS_FILES:$(LOCAL_PATH)/%=%)
FRAMEWORK_GRAPHICS_FILES += TaxiCode/Framework/Graphics/Android/ImageLoader.cpp

FRAMEWORK_GRAPHICS_CONTENT_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Graphics/Content/*.cpp)
FRAMEWORK_GRAPHICS_CONTENT_FILES := $(FRAMEWORK_GRAPHICS_CONTENT_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_IO_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/IO/*.cpp)
FRAMEWORK_IO_FILES := $(FRAMEWORK_IO_FILES:$(LOCAL_PATH)/%=%)
FRAMEWORK_IO_FILES += TaxiCode/Framework/IO/Android/Path.cpp

FRAMEWORK_UTILS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Utils/*.cpp)
FRAMEWORK_UTILS_FILES := $(FRAMEWORK_UTILS_FILES:$(LOCAL_PATH)/%=%)
FRAMEWORK_UTILS_FILES += TaxiCode/Framework/Utils/Android/Log.cpp

FRAMEWORK_ANALYTICS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Analytics/*.cpp)
FRAMEWORK_ANALYTICS_FILES := $(FRAMEWORK_ANALYTICS_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_XML_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/XML/*.cpp)
FRAMEWORK_XML_FILES := $(FRAMEWORK_XML_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_ADS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Ads/*.cpp)
FRAMEWORK_ADS_FILES := $(FRAMEWORK_ADS_FILES:$(LOCAL_PATH)/%=%)

FRAMEWORK_AUDIO_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Framework/Audio/*.cpp)
FRAMEWORK_AUDIO_FILES := $(FRAMEWORK_AUDIO_FILES:$(LOCAL_PATH)/%=%)

EXT_TINYXML_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Ext/tinyxml/*.cpp)
EXT_TINYXML_FILES := $(EXT_TINYXML_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/*.cpp)
BUNNIES_FILES := $(BUNNIES_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_EFFECTS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/Effects/*.cpp)
BUNNIES_EFFECTS_FILES := $(BUNNIES_EFFECTS_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_BONUSES_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/Bonuses/*.cpp)
BUNNIES_BONUSES_FILES := $(BUNNIES_BONUSES_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_ANALYTICSEVENTS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/AnalyticsEvents/*.cpp)
BUNNIES_ANALYTICSEVENTS_FILES := $(BUNNIES_ANALYTICSEVENTS_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_GUI_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/Gui/*.cpp)
BUNNIES_GUI_FILES := $(BUNNIES_GUI_FILES:$(LOCAL_PATH)/%=%)

BUNNIES_REMOTEGAMEDATAACCESS_FILES := $(wildcard $(LOCAL_PATH)/TaxiCode/Bunnies/RemoteGameDataAccess/*.cpp)
BUNNIES_REMOTEGAMEDATAACCESS_FILES := $(BUNNIES_REMOTEGAMEDATAACCESS_FILES:$(LOCAL_PATH)/%=%)
BUNNIES_REMOTEGAMEDATAACCESS_FILES += TaxiCode/Bunnies/RemoteGameDataAccess/Android/RemoteDataAccessFactory.cpp

LOCAL_MODULE    := libtaxisoftlaunch
LOCAL_SRC_FILES := $(ROOT_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_MATH_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_IO_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_UTILS_FILES)
LOCAL_SRC_FILES += $(EXT_TINYXML_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_XML_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_ANALYTICS_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_GRAPHICS_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_GRAPHICS_CONTENT_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_ADS_FILES)
LOCAL_SRC_FILES += $(FRAMEWORK_AUDIO_FILES)
LOCAL_SRC_FILES += $(BUNNIES_FILES)
LOCAL_SRC_FILES += $(BUNNIES_EFFECTS_FILES)
LOCAL_SRC_FILES += $(BUNNIES_BONUSES_FILES)
LOCAL_SRC_FILES += $(BUNNIES_ANALYTICSEVENTS_FILES)
LOCAL_SRC_FILES += $(BUNNIES_GUI_FILES)
LOCAL_SRC_FILES += $(BUNNIES_REMOTEGAMEDATAACCESS_FILES)

LOCAL_LDLIBS := -llog -lGLESv2 -landroid
LOCAL_SHARED_LIBRARIES := libfmod

LOCAL_C_INCLUDES := $(LOCAL_PATH)/TaxiCode/Framework
LOCAL_C_INCLUDES += $(LOCAL_PATH)/TaxiCode/Ext

include $(BUILD_SHARED_LIBRARY)

